<?xml version="1.0" encoding="windows-1251" ?>
<!DOCTYPE Types [
<!ELEMENT Types (type*)>
<!ELEMENT type (attribs*,methods*,handlers*)>
	<!ATTLIST type 
		name NMTOKEN #REQUIRED
		alias CDATA #IMPLIED
		base CDATA #IMPLIED
		creatable CDATA #IMPLIED
		components CDATA #IMPLIED
		abstract CDATA #IMPLIED
	>
<!ELEMENT attribs (attrib+)>
<!ELEMENT attrib (#PCDATA)*>
	<!ATTLIST attrib
		name 	CDATA #REQUIRED
		alias 	CDATA 	#IMPLIED
		type 	CDATA 	#IMPLIED
		InExprOnly CDATA 	#IMPLIED
		components CDATA #IMPLIED
	>
<!ELEMENT methods (method+)>
<!ELEMENT method (#PCDATA|params|return)*>
	<!ATTLIST method
		name 	CDATA	#REQUIRED
		alias 	CDATA 	#IMPLIED
		components CDATA #IMPLIED
	>
<!ELEMENT params (param+)>
<!ELEMENT param (#PCDATA)>
	<!ATTLIST param
		name 	CDATA	#REQUIRED
		type	CDATA	#IMPLIED
		default	CDATA	#IMPLIED
	>
<!ELEMENT return (#PCDATA)>
	<!ATTLIST return
		type	CDATA	#IMPLIED
		InExprOnly CDATA 	#IMPLIED
	>
<!ELEMENT handlers (method+)>
]>
<!--
Требуется:
1. Проставить где возможно типы атрибутов, параметров, возвращаемых значений.
2. Для необязательных параметров проставить значение по умолчанию default=.
3. Для обязательных параметров УДАЛИТЬ атрибут default=
4. Для процедур УДАЛИТЬ тэг <return></return>
5. Проверить, везде ли правильно проставлены параметры, нет ли лишних или недостающих.
6. Сгруппировать отдельно методы, применяемые только для объектов, созданных СоздатьОбъект.
-->
<Types>
	<!--Базовые типы данных
	<type name="Number" alias="Число">
		Число
	</type>
	<type name="Date" alias="Дата">
		Дата - будет выпадать список функций, возвращающих дату, и стандартный 1С контрол - выбор даты
	</type>
	<type name="String" alias="Строка">
		Строка
	</type>
	<type name="FileName">
		путь/имя файла	- будет выпадать список функций, возвращающих путь имя и диалог открытия файла
	</type>
	<type name="FormatString">
		Форматная строка - возможно, будет выпадать конструктор форматной строки
	</type>
	<type name="RefSort">
		Поле справочника с признаком сортировка - будет выпадать
		список реквизитов справочника с признаком сортировка,
		если тип справочника не удасться определелить, выпадет список
		таких реквизитов для всех справочников.
	</type>
	<type name="RefSel">
		Поле справочника с признаком отбор - аналогично
	</type>
	<type name="DocTotal">
		Поле документа с признаком Итог по колонке
	</type>
	<type name="DocSel">
		Вид отбора документов - будет падать список возможных отборов доков.
	</type>
	<type name="RegFigures">
		Измерения регистра
	</type>
	<type name="RegResource">
		Ресурсы регистра
	</type>
	<type name="RegAttrib">
		Реквизиты регистра
	</type>
	Возможно, ченить еще...
	Допускается через запятую указывать несколько типов.
	Например,
	<param name="Идентиф" type="RegFigures,RegAttrib">идентификатор измерения или реквизита</param>
	будет выпадать список измерений и реквизитов регистра.
	-->
	<type name="Global">
		<attribs>
			<attrib name="РазделительСтраниц" alias="PageBreak" type="String" InExprOnly="1">
				Символ перевода страницы текста
			</attrib>
			<attrib name="РазделительСтрок" alias="LineBreak" type="String" InExprOnly="1">
				Символ перевода строки текста
			</attrib>
			<attrib name="СимволТабуляции" alias="TabSymbol" type="String" InExprOnly="1">
				Символ табуляции текста
			</attrib>
			<attrib name="Перечисление" alias="Enum" type="AllEnum" InExprOnly="1">
				Глобальный объект для доступа к перечислениям
			</attrib>
			<attrib name="Константа" alias="Const" type="AllConst">
				Глобальный объект для доступа к константам
			</attrib>
			<attrib name="Последовательность" alias="Sequence" type="Sequences">
				Глобальный объект &quot;Последовательность&quot;
			</attrib>
			<attrib name="ФС" alias="FS" type="FS">
				Глобальный объект &quot;Файловая система&quot;
			</attrib>
			<attrib name="Метаданные" alias="MetaData" type="MetaData" InExprOnly="1">
				Глобальный объект &quot;Метаданные&quot;
			</attrib>
			<attrib name="Регистр" alias="Register" type="AllRegs" InExprOnly="1" components="1">
				Глобальный объект &quot;Регистры&quot;
			</attrib>
			<attrib name="ПланыСчетов" alias="ChartsOfAccounts" type="ChartsOfAccounts" InExprOnly="1" components="2">
				Глобальный объект &quot;ПланыСчетов&quot;
			</attrib>
			<attrib name="ВидыСубконто" alias="SubcontoKinds" type="SubcontoKinds" InExprOnly="1" components="2">
				Глобальный объект &quot;ВидыСубконто&quot;
			</attrib>
			<attrib name="ВидРасчета" alias="Calculation" type="Calculation" InExprOnly="1" components="4">
				Глобальный объект &quot;ВидРасчета&quot;
			</attrib>
			<attrib name="ГруппаРасчетов" alias="CalculationGroup" type="CalculationGroup" InExprOnly="1" components="4">
				Глобальный объект &quot;ГруппаРасчетов&quot;
			</attrib>
			<attrib name="ПравилоПерерасчета" alias="ReCalculationRule" type="ReCalculationRule" components="4">
				Глобальный объект &quot;ПравилоПерерасчета&quot;
			</attrib>
			<attrib name="Календари" alias="Calendars" type="Calendars" components="4">
				Глобальный объект &quot;Календари&quot;
			</attrib>
		</attribs>
		<methods>
			<method name="ИБСозданияОбъекта" alias="BirthIBOfObject" components="8">
				Определить ИБ, создавшую объект
				<params>
					<param name="Объект">
						Элемент справочника, документ или бухгалтерский счет
					</param>
				</params>
				<return type="String">
					код ИБ, на которой был создан первоначально объект
				</return>
			</method>
			<method name="ТекущаяИБКод" alias="CurrentIBCode" components="8">
				Получить код текущей ИБ
				<return type="String">
					код ИБ, на которой запущена система 1С:Предприятие
				</return>
			</method>
			<method name="ТекущаяИБНаименование" alias="CurrentIBDescr" components="8">
				Получить наименование текущей ИБ
				<return type="String">
					возвращает наименование ИБ, на которой запущена система 1С:Предприятие
				</return>
			</method>
			<method name="ТекущаяИБТолькоПолучатель" alias="IsCurrentIBRecepientOnly" components="8">
				Определить имеет ли текущая ИБ признак &quot;Только получатель&quot;
				<return type="0;1">
					1-имеет признак &quot;Только получатель&quot;, 0-нет
				</return>
			</method>
			<method name="ТекущаяИБЦентральная" alias="IsCurrentIBCenter" components="8">
				Определить, является ли текущая ИБ центральной
				<return type="0;1">
					1-центральная, 0-периферийная
				</return>
			</method>
			<method name="ЦентральнаяИБКод" alias="CentralIBCode" components="8">
				<return type="String">
					код центральной ИБ
				</return>
			</method>
			<method name="ЗагрузитьВнешнююКомпоненту" alias="LoadAddIn">
				Загружает внешнюю компоненту
				<params>
					<param name="Путь" type="FileName">Путь ко внешней компоненте</param>
				</params>
				<return type="0;1">
					0-не загружена, 1-загружена
				</return>
			</method>					
			<method name="_StrToId" alias="_StrToId">
				<params>
					<param name="Str" type="String"></param>
				</params>
				<return type="Number" InExprOnly="1">
				</return>
			</method>					
			<method name="_IdToStr" alias="_IdToStr">
				<params>
					<param name="ID" type="Number"></param>
				</params>
				<return type="Number" InExprOnly="1">
				</return>
			</method>					
			<method name="_GetPerformanceCounter" alias="_GetPerformanceCounter">
				<return type="Number" InExprOnly="1">
					Количество милисекунд с момента запуска системы
				</return>
			</method>					
			<method name="Окр" alias="Round">
				<params>
					<param name="Число1" type="Number">
						число, которое надо округлить
					</param>
					<param name="Число2" type="Number" default="0">
						точность
					</param>
					<param name="Способ" type="0;1" default="">
						0-если 1.5 округляется до 1, 1-если 1.5 округляется до 2
					</param>
				</params>
				<return type="Number" InExprOnly="1">
					значение результата округления
				</return>
			</method>
			<method name="Цел" alias="Int">
				<params>
					<param name="Число" type="Number">
						числовое выражение
					</param>
				</params>
				<return type="Number" InExprOnly="1">
					значение целой части параметра
				</return>
			</method>
			<method name="Мин" alias="Min">
				<params>
					<param name="Элемент1" type="Number">
						список выражений базовых типов данных
					</param>
					<param name="ЭлементN" type="Number">
					</param>
				</params>
				<return type="Number" InExprOnly="1">
					значение наименьшего параметра
				</return>
			</method>
			<method name="Макс" alias="Max">
				<params>
					<param name="Элемент1" type="Number">
						список выражений базовых типов данных
					</param>
					<param name="ЭлементN" type="Number">
					</param>
				</params>
				<return type="Number" InExprOnly="1">
					значение наибольшего параметра
				</return>
			</method>
			<method name="Лог10" alias="Log10">
				<params>
					<param name="Число" type="Number">
						числовое выражение
					</param>
				</params>
				<return type="Number" InExprOnly="1">
					значение десятичного логарифма параметра
				</return>
			</method>
			<method name="Лог" alias="Ln">
				<params>
					<param name="Число" type="Number">
						числовое выражение
					</param>
				</params>
				<return type="Number" InExprOnly="1">
					значение натурального логарифма параметра
				</return>
			</method>
			<method name="СтрДлина" alias="StrLen">
				<params>
					<param name="Строка" type="String">
						строковое выражение
					</param>
				</params>
				<return type="Number" InExprOnly="1">
					длину строки
				</return>
			</method>
			<method name="ПустаяСтрока" alias="IsBlankString">
				Проверить строку на наличие значащих символов
				<params>
					<param name="Строка" type="String">
						строковое выражение
					</param>
				</params>
				<return type="0;1" InExprOnly="1">
					1-строка пустая или содержит только пробелы, 0-иначе
				</return>
			</method>
			<method name="СокрЛ" alias="TrimL">
				<params>
					<param name="Строка" type="String">
						строковое выражение
					</param>
				</params>
				<return type="String" InExprOnly="1">
					cтроку, полученную из параметра отсечением левых пробелов
				</return>
			</method>
			<method name="СокрП" alias="TrimR">
				<params>
					<param name="Строка" type="String">
						строковое выражение
					</param>
				</params>
				<return type="String" InExprOnly="1">
					cтроку, полученную из параметра отсечением правых пробелов
				</return>
			</method>
			<method name="СокрЛП" alias="TrimAll">
				Отсекает стоящие слева и справа пробелы
				<params>
					<param name="Строка" type="String">
						строковое выражение
					</param>
				</params>
				<return type="String" InExprOnly="1">
					результирующую строку
				</return>
			</method>
			<method name="Лев" alias="Left">
				<params>
					<param name="Строка" type="String">
						строковое выражение
					</param>
					<param name="Число" type="Number">
						количество возвращаемых символов
					</param>
				</params>
				<return type="String" InExprOnly="1">
					cтроку, содержащую первые символы текстовой строки
				</return>
			</method>
			<method name="Прав" alias="Right">
				<params>
					<param name="Строка" type="String">
						строковое выражение
					</param>
					<param name="Число" type="Number">
						количество возвращаемых символов
					</param>
				</params>
				<return type="String" InExprOnly="1">
					cтроку, содержащую последние символы текстовой строки
				</return>
			</method>
			<method name="Сред" alias="Mid">
				<params>
					<param name="Строка" type="String">
						строковое выражение
					</param>
					<param name="Число1" type="Number">
						позиция первого символа (начиная с 1)
					</param>
					<param name="Число2" type="Number" default="">
						количество возвращаемых символов (если опущен, то до конца строки)
					</param>
				</params>
				<return type="String" InExprOnly="1">
					подcтроку, заданную номером  позиции и числом символов
				</return>
			</method>
			<method name="Найти" alias="Find">
				<params>
					<param name="Строка1" type="String">
						строка, в которой ищем
					</param>
					<param name="Строка2" type="String">
						строка которую ищем
					</param>
				</params>
				<return type="Number" InExprOnly="1">
					позицию первого вхождения заданной подстроки
				</return>
			</method>
			<method name="СтрЗаменить" alias="StrReplace">
				<params>
					<param name="СтрИсточник" type="String">
						строка, в которой ищем
					</param>
					<param name="СтрПодстрока" type="String">
						строка, которую ищем
					</param>
					<param name="СтрЗамены" type="String">
						строка, которой заменяем
					</param>
				</params>
				<return type="String" InExprOnly="1">
					строку, полученную из строки поиска заменой всех вхождений шаблона поиска строкой замены
				</return>
			</method>
			<method name="СтрЧислоВхождений" alias="StrCountOccur">
				<params>
					<param name="СтрИсточник" type="String">
						строка, в которой ищем
					</param>
					<param name="СтрПодстрока" type="String">
						строка, которую ищем
					</param>
				</params>
				<return type="Number" InExprOnly="1">
					число вхождений строки шаблона поиска в строку поиска
				</return>
			</method>
			<method name="СтрКоличествоСтрок" alias="StrLineCount">
				<params>
					<param name="Строка" type="String">
						строковое выражение
					</param>
				</params>
				<return type="Number" InExprOnly="1">
					число строк в многострочном тексте
				</return>
			</method>
			<method name="СтрПолучитьСтроку" alias="StrGetLine">
				<params>
					<param name="Текст" type="String">
						строковое выражение
					</param>
					<param name="НомерСтроки" type="Number">
						номер строки
					</param>
				</params>
				<return type="String" InExprOnly="1">
					строку из многострочного текста по заданному номеру
				</return>
			</method>
			<method name="Врег" alias="Upper">
				<params>
					<param name="Строка" type="String">
						исходная строка
					</param>
				</params>
				<return type="String" InExprOnly="1">
					строку, преобразованую в верхний регистр
				</return>
			</method>
			<method name="Нрег" alias="Lower">
				<params>
					<param name="Строка" type="String">
						исходная строка
					</param>
				</params>
				<return type="String" InExprOnly="1">
					строку, преобразованную в нижний регистр
				</return>
			</method>
			<method name="OemToAnsi" alias="OemToAnsi">
				<params>
					<param name="Строка" type="String">
						исходная строка
					</param>
				</params>
				<return type="String" InExprOnly="1">
					строку, преобразованную в кодировку Ansi
				</return>
			</method>
			<method name="AnsiToOem" alias="AnsiToOem">
				<params>
					<param name="Строка" type="String">
						исходная строка
					</param>
				</params>
				<return type="String" InExprOnly="1">
					строку, преобразованную в кодировку Oem
				</return>
			</method>
			<method name="Симв" alias="Chr">
				<params>
					<param name="КодСимвола" type="Number">
						числовое значение кода символа
					</param>
				</params>
				<return type="String" InExprOnly="1">
					строку, содержащую символ с заданным кодом
				</return>
			</method>
			<method name="КодСимв" alias="Asc">
				<params>
					<param name="Символ" type="String">
						строковое выражение
					</param>
				</params>
				<return type="Number" InExprOnly="1">
					код первого символа
				</return>
			</method>
			<method name="РабочаяДата" alias="WorkingDate">
				Устанавливает значение рабочей даты
				<params>
					<param name="Дата" type="Date" default="">
						Выражение типа дата
					</param>
					<param name="РежимСменыРабДаты" type="0;1;2" default="">
						Режим автоматической смены рабочей даты в полночь:0-не менять, 1-менять с предупреждением, 2-менять автоматически без предупреждения
					</param>
				</params>
				<return type="Date">
					значение рабочей даты
				</return>
			</method>
			<method name="ТекущаяДата" alias="CurDate">
				<return type="Date" InExprOnly="1">
					текущую системную дату
				</return>
			</method>
			<method name="ДобавитьМесяц" alias="AddMonth">
				<params>
					<param name="Дата" type="Date">
						выражение типа дата
					</param>
					<param name="ЧислоМесяцев" type="Number">
						число месяцев, добавляемое к дате
					</param>
				</params>
				<return type="Date" InExprOnly="1">
					дату, полученную добавлением к исходной дате заданного числа месяцев
				</return>
			</method>
			<method name="НачМесяца" alias="BegOfMonth">
				<params>
					<param name="Дата" type="Date">
						выражение типа дата
					</param>
				</params>
				<return type="Date" InExprOnly="1">
					дату начала месяца для заданной даты
				</return>
			</method>
			<method name="КонМесяца" alias="EndOfMonth">
				<params>
					<param name="Дата" type="Date">
						выражение типа дата
					</param>
				</params>
				<return type="Date" InExprOnly="1">
					дату конца месяца для заданной даты
				</return>
			</method>
			<method name="НачКвартала" alias="BegOfQuart">
				<params>
					<param name="Дата" type="Date">
						выражение типа дата
					</param>
				</params>
				<return type="Date" InExprOnly="1">
					дату начала квартала для заданной даты
				</return>
			</method>
			<method name="КонКвартала" alias="EndOfQuart">
				<params>
					<param name="Дата" type="Date">
						выражение типа дата
					</param>
				</params>
				<return type="Date" InExprOnly="1">
					дату конца квартала для заданной даты
				</return>
			</method>
			<method name="НачГода" alias="BegOfYear">
				<params>
					<param name="Дата" type="Date">
						выражение типа дата
					</param>
				</params>
				<return type="Date" InExprOnly="1">
					дату начала года для заданной даты
				</return>
			</method>
			<method name="КонГода" alias="EndOfYear">
				<params>
					<param name="Дата" type="Date">
						выражение типа дата
					</param>
				</params>
				<return type="Date" InExprOnly="1">
					дату конца года для заданной даты
				</return>
			</method>
			<method name="НачНедели" alias="BegOfWeek">
				<params>
					<param name="Дата" type="Date">
						выражение типа дата
					</param>
				</params>
				<return type="Date" InExprOnly="1">
					дату начала недели для заданной даты
				</return>
			</method>
			<method name="КонНедели" alias="EndOfWeek">
				<params>
					<param name="Дата" type="Date">
						выражение типа дата
					</param>
				</params>
				<return type="Date" InExprOnly="1">
					дату конца недели для заданной даты
				</return>
			</method>
			<method name="ДатаГод" alias="GetYear">
				<params>
					<param name="Дата" type="Date">
						выражение типа дата
					</param>
				</params>
				<return type="Number" InExprOnly="1">
					числовое значение года для заданной даты
				</return>
			</method>
			<method name="ДатаМесяц" alias="GetMonth">
				<params>
					<param name="Дата" type="Date">
						выражение типа дата
					</param>
				</params>
				<return type="Number" InExprOnly="1">
					числовое значение месяца для заданной даты
				</return>
			</method>
			<method name="ДатаЧисло" alias="GetDay">
				<params>
					<param name="Дата" type="Date">
						выражение типа дата
					</param>
				</params>
				<return type="Number" InExprOnly="1">
					числовое значение дня месяца для заданной даты
				</return>
			</method>
			<method name="НомерНеделиГода" alias="GetWeekOfYear">
				<params>
					<param name="Дата" type="Date">
						выражение типа дата
					</param>
				</params>
				<return type="Date" InExprOnly="1">
					номер недели в году для заданной даты
				</return>
			</method>
			<method name="НомерДняГода" alias="GetDayOfYear">
				<params>
					<param name="Дата" type="Date">
						выражение типа дата
					</param>
				</params>
				<return type="Number" InExprOnly="1">
					порядковый номер дня в году для заданной даты
				</return>
			</method>
			<method name="НомерДняНедели" alias="GetDayOfWeek">
				<params>
					<param name="Дата" type="Date">
						выражение типа дата
					</param>
				</params>
				<return type="Number" InExprOnly="1">
					порядковый номер дня недели для заданной даты
				</return>
			</method>
			<method name="ПериодСтр" alias="PeriodStr">
				<params>
					<param name="ДатаНачалаПериода" type="Date">
						Начальная дата периода
					</param>
					<param name="ДатаКонцаПериода"  type="Date">
						Конечная  дата периода
					</param>
				</params>
				<return type="String" InExprOnly="1">
					информацию о периоде бухгалтерских итогов в виде строки символов
				</return>
			</method>
			<method name="НачалоСтандартногоИнтервала" alias="BegOfStandardRange">
				Устанавливает вариант задания стандартного начала интервала отображения журнала документов
				<params>
					<param name="Вариант" type="Date1" default="">
						Выражение со значением типа строка или дата
					</param>
				</params>
				<return type="Date1">
					текущий установленный вариант
				</return>
			</method>
			<method name="КонецСтандартногоИнтервала" alias="EndOfStandardRange">
				Устанавливает вариант задания стандартного конца интервала отображения журнала документов
				<params>
					<param name="Вариант" type="Date1" default="">
						Выражение со значением типа строка или дата
					</param>
				</params>
				<return type="Date1">
					текущий установленный вариант
				</return>
			</method>
			<method name="ТекущееВремя" alias="CurrentTime">
				<params>
					<param name="Час" type="VarName" default="">
						имя переменной для получения числа часов текущего времени
					</param>
					<param name="Мин" type="VarName" default="">
						имя переменной для получения числа минут текущего времени
					</param>
					<param name="Сек" type="VarName" default="">
						имя переменной для получения числа секунд текущего времени
					</param>
				</params>
				<return type="String">
					текущее (системное) время в текстовом виде
				</return>
			</method>
			<method name="СформироватьПозициюДокумента" alias="MakeDocPosition">
				<params>
					<param name="Докум" type="Document,Position">
						значение документа (или его позиция), позиция которого определяется
					</param>
					<param name="ФлагСмещения" type="-1;0;1" default="0">
						-1- предыдущая позиция, 1-следующая позиция, 0-текущая позиция
					</param>
				</params>
				<return type="Position" InExprOnly="1">
					позицию документа согласно переданным параметрам
				</return>
			</method>
			<method name="СформироватьПозициюДокумента" alias="MakeDocPosition">
				<params>
					<param name="Дата" type="Date">
						дата, на которую формируется позиция документа
					</param>
					<param name="Час" type="Number">
						час, на который формируется позиция документа
					</param>
					<param name="Мин" type="Number">
						минута, на которую формируется позиция документа
					</param>
					<param name="Сек" type="Number">
						секунда, на которую формируется позиция документа
					</param>
					<param name="ФлагКонцаСекунды" type="0;1" default="0">
						1-позиция будет браться от следующей секунды, 0-позиция от указанной секунды
					</param>
				</params>
				<return type="Position" InExprOnly="1">
					позицию документа согласно переданным параметрам
				</return>
			</method>
			<method name="РазобратьПозициюДокумента" alias="SplitDocPosition">
				Раскладывает позицию документа на составляющие
				<params>
					<param name="Позиция" type="Position">
						строковое значение позиции документа
					</param>
					<param name="Дата" type="VarName" default="">
						Имя переменной, куда система вернет значение даты позиции документа
					</param>
					<param name="Час" type="VarName" default="">
						Имя переменной, куда система вернет час позиции документа
					</param>
					<param name="Мин" type="VarName" default="">
						Имя переменной, куда система вернет минуту позиции документа
					</param>
					<param name="Сек" type="VarName" default="">
						Имя переменной, куда система вернет секунду позиции документа
					</param>
					<param name="Документ" type="VarName" default="">
						 Имя переменной, куда система вернет документ данной позиции документа
					</param>
				</params>
				<return type="String">
					строковое представление позиции документа
				</return>
			</method>
			<method name="Дата" alias="Date">
				<params>
					<param name="Параметр">
						выражение
					</param>
				</params>
				<return type="Date" InExprOnly="1">
					результат преобразования параметра в дату по правилам преобразования типов
				</return>
			</method>
			<method name="Дата" alias="Date">
				Преобразует Год, Месяц, Число в значение типа &quot;Дата&quot;
				<params>
					<param name="Год" type="Number">
						указывается 4-х значным числом (вместе с веком)
					</param>
					<param name="Месяц" type="Number">
						числовое выражение
					</param>
					<param name="Число" type="Number">
						числовое выражение
					</param>
				</params>
				<return type="Date" InExprOnly="1">
				</return>
			</method>
			<method name="Строка" alias="String">
				<params>
					<param name="Параметр">
						выражение
					</param>
				</params>
				<return type="String" InExprOnly="1">
					результат преобразования параметра в строку по правилам преобразования типов
				</return>
			</method>
			<method name="Число" alias="Number">
				<params>
					<param name="Параметр">
						выражение
					</param>
				</params>
				<return type="Number" InExprOnly="1">
					результат преобразования параметра в число по правилам преобразования типов
				</return>
			</method>
			<method name="Пропись" alias="Spelling">
				Задать образец вывода чисел прописью
				<params>
					<param name="Параметр" type="FileName,ValueList">
						строка, содержащая имя файла с прописью (если в параметре передано &quot;&quot;, то устанавливается пропись по умолчанию) или объект типа &quot;СписокЗначений&quot;, в котором лежат строки, структура которых совпадает со структурой файла прописей
					</param>
				</params>
			</method>
			<method name="Формат" alias="Format">
				<params>
					<param name="Параметр">
						форматируемое выражение
					</param>
					<param name="ФорматнаяСтрока" type="FormatString">
						форматная строка
					</param>
				</params>
				<return type="String" InExprOnly="1">
					строку с результатом форматирования выражения по заданной форматной строке
				</return>
			</method>
			<method name="Шаблон" alias="Template">
				<params>
					<param name="СтрокаШаблон" type="String">
						строка, содержащая шаблон формирования
					</param>
				</params>
				<return type="String">
					строку, полученную по шаблону заменой встроенных выражений на значения и форматированием
				</return>
			</method>
			<method name="ФиксШаблон" alias="FixTemplate">
				<params>
					<param name="СтрокаШаблон" type="String">
						строка, содержащая шаблон формирования
					</param>
				</params>
				<return type="String">
					строку, полученную по шаблону заменой встроенных выражений на значения и форматированием, с сохранением длин содержащих их полей
				</return>
			</method>
			<method name="ВвестиЗначение" alias="InputValue">
				Вызов диалога для ввода значения заданного типа
				<params>
					<param name="Значение" type="VarName">
						имя переменной для приема вводимого значения
					</param>
					<param name="Подсказка" type="String">
						текст заголовка окна диалога ввода
					</param>
					<param name="Тип" type="TypeString">
						название типа данных, которое требутся ввести
					</param>
					<param name="Длина" type="Number" default="">
						длина вводимого значения
					</param>
					<param name="Точность" type="Number" default="">
						число знаков после десятичной точки
					</param>
				</params>
				<return type="0;1">
					1-в диалоге нажата кнопка &quot;ОК&quot;, 0-нажата кнопка &quot;Отмена&quot;
				</return>
			</method>
			<method name="ВвестиЧисло" alias="InputNumeric">
				Вызов диалога для ввода числа
				<params>
					<param name="Число" type="VarName">
						имя переменной для приема вводимого значения
					</param>
					<param name="Подсказка" type="String">
						текст заголовка окна диалога ввода
					</param>
					<param name="Длина" type="Number">
						длина вводимого числа
					</param>
					<param name="Точность" type="Number">
						число знаков после десятичной точки
					</param>
					<param name="Таймаут" type="Number" default="0">
						число секунд времени ожидания ответа
					</param>
				</params>
				<return type="-1;0;1">
					1-в диалоге нажата кнопка &quot;ОК&quot;, 0-нажата кнопка &quot;Отмена&quot;, -1- закончилось время ожидания ответа
				</return>
			</method>
			<method name="ВвестиСтроку" alias="InputString">
				Вызов диалога для ввода строки
				<params>
					<param name="Строка" type="VarName">
						имя переменной для приема вводимого значения
					</param>
					<param name="Подсказка" type="String">
						текст заголовка окна диалога ввода
					</param>
					<param name="ДлинаСтроки" type="Number">
						длина вводимой строки
					</param>
					<param name="Признак" type="0;1" default="0">